# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-05 20:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fornecedor', '0001_initial'),
        ('produto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemNota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(verbose_name='Quantidade')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_entrada', models.DateTimeField(verbose_name='Entrada')),
                ('data_emissao', models.DateTimeField(verbose_name='Emissão')),
                ('total', models.DecimalField(decimal_places=2, editable=False, max_digits=7, verbose_name='Total')),
                ('status', models.CharField(choices=[('A', 'Em aberto'), ('C', 'Cancelada'), ('P', 'Processada')], default='A', max_length=1, verbose_name='Status')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criada em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizada em')),
            ],
        ),
        migrations.CreateModel(
            name='NotaEntrada',
            fields=[
                ('nota_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='estoque.Nota')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('tipo_entrada', models.CharField(choices=[('C', 'Compra'), ('G', 'Garantia')], max_length=1, verbose_name='Tipo de entrada')),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entradas', to='fornecedor.Fornecedor', verbose_name='Fornecedor')),
            ],
            options={
                'verbose_name': 'Entrada',
                'verbose_name_plural': 'Entradas',
                'ordering': ['data_entrada'],
            },
            bases=('estoque.nota',),
        ),
        migrations.AddField(
            model_name='itemnota',
            name='nota',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itensNota', to='estoque.Nota', verbose_name='Nota'),
        ),
        migrations.AddField(
            model_name='itemnota',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itensNota', to='produto.Produto', verbose_name='Produto'),
        ),
    ]
