# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-05 20:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemnota',
            options={'ordering': ['produto', 'quantidade'],
                     'verbose_name': 'Item nota', 'verbose_name_plural': 'Itens nota'},
        ),
        migrations.RemoveField(
            model_name='itemnota',
            name='nota',
        ),
    ]
