# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-05 20:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0003_auto_20180205_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nota',
            name='total',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=7, null=True, verbose_name='Total'),
        ),
    ]
