# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-05 20:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0004_auto_20180205_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemnota',
            name='id',
            field=models.AutoField(
                auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='itemnota',
            name='nota',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    related_name='itensNota', to='estoque.Nota', verbose_name='Nota'),
        ),
    ]
