# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-06 16:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0008_auto_20180206_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nota',
            name='total',
            field=models.DecimalField(
                decimal_places=2, default=0, editable=False, max_digits=7, verbose_name='Total'),
        ),
    ]
