language: python
python:
  - "3.6"
  - "3.7-dev"  # 3.7 development branch
# command to install dependencies
install:
  - pip install -r requirements_tests.txt
# command to run tests
script:
#  - pytest # or py.test for Python versions 3.5 and below
   - flake8

