# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-02 20:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientePF',
            fields=[
                ('pessoafisica_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.PessoaFisica')),
            ],
            options={
                'verbose_name': 'Cliente (PF)',
                'verbose_name_plural': 'Clientes (PF)',
                'ordering': ['nome'],
            },
            bases=('core.pessoafisica',),
        ),
    ]
